server:
  port: 8001

JWT_SECRET: ${JWT-SECRET}
JWT_EXPIRATION_MS: ${JWT-EXPIRATION-MS}

spring:
  application:

    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://${MYSQL-URL}/${MYSQL-DATABASE}?allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
    username: ${MYSQL-USERNAME}
    password: ${MYSQL-PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL-AUTO}
    properties:
      hibernate:
        dialect: ${DIALECT}
    generate-ddl: ${GENERATED-DDL}
    defer-datasource-initialization: ${DATASOURCE-INITIALIZATION}
  sql:
    init:
      platform: ${PLATFORM}
      mode: ${MODE}

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: localhost