version: '2.3'

services:

#  mysql-db:
#    image: mysql
#    healthcheck:
#      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
#      timeout: 20s
#      retries: 10
#    environment:
#      MYSQL_ROOT_PASSWORD: "${MYSQL-ROOT-PASSWORD}"
#      MYSQL_DATABASE: "${MYSQL-DATABASE}"
#      MYSQL_USER: "${MYSQL-USERNAME}"
#      MYSQL_PASSWORD: "${MYSQL-PASSWORD}"
#    ports:
#      - "3307:3306"
#    restart: on-failure
#    volumes:
#      - db:/var/lib/mysql
#    cap_add:
#      - SYS_NICE

  web-app:
#    depends_on:
#      mysql-db:
#        condition: service_healthy
    build: .
    restart: on-failure
    ports:
      - "8001:8001"
#    environment:
#      SPRING_APPLICATION_JSON: '{
#        "spring.datasource.url"  : "jdbc:mysql://${MYSQL-URL}/${MYSQL-DATABASE}?allowPublicKeyRetrieval=true&useSSL=false",
#        "spring.datasource.username" : "${MYSQL-USERNAME}",
#        "spring.datasource.password" : "${MYSQL-PASSWORD}",
#        "spring.jpa.properties.hibernate.dialect" : "${DIALECT}",
#        "spring.jpa.hibernate.ddl-auto" : "${DDL-AUTO}",
#        "spring.jpa.generate-ddl" : "${GENERATED-DDL}",
#        "spring.jpa.defer-datasource-initialization" : "${DATASOURCE-INITIALIZATION}",
#        "spring.sql.init.platform" : "${PLATFORM}",
#        "spring.sql.init.mode" : "${MODE}",
#        "JWT_SECRET" : "${JWT-SECRET}",
#        "JWT_EXPIRATION_MS" : "${JWT-EXPIRATION-MS}"
#        }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true

volumes:
  db: